name: eods
channels:
  - conda-forge
dependencies:
  - python==3.8.8
  - pandas==1.2.4
  - notebook==6.3.0
  - requests==2.25.1
  - rasterio==1.2.3
  - matplotlib==3.4.1
  - shapely==1.7.1
  - pyproj==3.0.1
  - xmltodict==0.12.0
  - python-dotenv==0.17.1